config/routes.rb
Rails.application.routes.draw do
  post 'set_location', to: 'locations#set'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Users Scopes
  scope module: "users" do 
    resources :profiles, only: %i[ show update edit ]

    resources :search, only: [ :index ]
    
    get '/developments/:id/render_description', to: 'developments#render_description', as: 'render_description'

    resources :developments, only: %i[ index show ] do
      resources :reviews do
        resources :scores
        resources :comments
      end
    end
  end
  
  # Moderation
  resources :moderator, only: %i[ index ]
  # Moderator Links
  namespace :moderator do
    resources :search, only: [ :index ]
    resources :developments do
      member do 
        patch :toggle_published
      end
      resources :reviews do
        resources :scores
        resources :comments
      end
    end
    # User management
    resources :users, only: %i[ index show ] do 
      member do
        patch :toggle_ban
      end
    end
  end


  # get 'admin', to: 'admin_panel#index'

  # Pages
  get "home", to: "pages#home"
  get "about_us", to: "pages#about"
  get "contact", to: "pages#contact"

  root 'pages#about'
end

app/controllers/developments_controller.rb
class DevelopmentsController < ApplicationController
  before_action :authenticate_user!, only: %i[ edit update destroy new create ]
  before_action :set_development, only: %i[ show edit update destroy render_description ]

  # GET /developments or /developments.json
  def index
    page = params[:page].to_i
    page = [page, 1].max
    @per_page = 3
    total_pages = (Development  .count / @per_page).ceil + 1
    # @page_numbers = (page - 2..page + 2).select { |num| num.positive? && num <= total_pages}
    # Calculate the range for @page_numbers
    nearest_count = 5
    start_number = [page - 2, 1].max
    end_number = [page + 2, total_pages].min

    # Adjust the start and end numbers if necessary
    if (end_number - start_number + 1) < nearest_count
      if page <= 3
        end_number = [start_number + nearest_count - 1, total_pages].min
      elsif page >= total_pages - 2
        start_number = [end_number - nearest_count + 1, 1].max
      else
        start_number = page - 2
        end_number = page + 2
      end
    end

    # Generate @page_numbers array
    @page_numbers = (start_number..end_number).to_a
    offset = (page - 1) * @per_page

    @developments = Development.limit(@per_page).offset(offset)

    @development_averages = @developments.each_with_object({}) do |development, averages|
      averages[development.id] = development.review_average
    end

    @development_averages = @developments.map { |development| [development.id, development.review_average] }.to_h
  end

  # GET /developments/1 or /developments/1.json
  def show
    @image = @development.current_image
    @average = @development.review_average
  end

  # GET /developments/new
  def new
    @development = Development.new
  end

  # GET /developments/1/edit
  def edit
  end

  # POST /developments or /developments.json
  def create
    @development = Development.new(development_params)

    respond_to do |format|
      if @development.save
        format.html { redirect_to development_url(@development), notice: "Development was successfully created." }
        format.json { render :show, status: :created, location: @development }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @development.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developments/1 or /developments/1.json
  def update
    respond_to do |format|
      if @development.update(development_params)
        format.html { redirect_to development_url(@development), notice: "Development was successfully updated." }
        format.json { render :show, status: :ok, location: @development }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @development.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developments/1 or /developments/1.json
  def destroy
    @development.destroy!

    respond_to do |format|
      format.html { redirect_to developments_url, notice: "Development was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def render_description
    render partial: "custom_description", locals: { development: @development }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_development
      @development = Development.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def development_params
      params.require(:development).permit(:name, :address, :acreage, :description, :website, :planned_start_date, :planned_end_date, :before_image, :after_image)
    end
end

app/controllers/moderator/developments_controller.rb
class Moderator::DevelopmentsController < ModeratorController
  before_action :set_development, only: %i[ edit update show destroy toggle_published ]
  before_action :require_admin_or_higher, only: %i[ destroy ]

  def index
    @pagy, @developments = pagy(Development.all, items: 3)
    @development_averages = @developments.map { |development| [development.id, development.review_average] }.to_h
  end

  def show
    @image = @development.current_image
    @average = @development.review_average
  end

  def edit
  end 

  def update
    if @development.update(development_params)
      redirect_to moderator_development_path(@development), notice: 'Development was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @development.destroy
    respond_to do |format|
      format.html
      format.turbo_stream
    end
    redirect_to moderator_developments_path
  end

  def toggle_published
    @development.update(published: !@development.published)
    respond_to do |format|
      format.html { redirect_to moderator_development_url(@development), notice: 'Development status was successfully updated.' }
      format.turbo_stream { redirect_to moderator_development_url(@development), notice: "Development status successfully updated." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_development
    @development = Development.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def development_params
    params.require(:development).permit(:name, :address, :acreage, :description, :website, :planned_start_date, :planned_end_date, :before_image, :after_image, :latitude, :longitude, address_attributes: [:id, :street_address, :city, :state, :postal_code, :country])
  end
end

app/controllers/moderator/users_controller.rb
class Moderator::UsersController < ApplicationController
  include ModeratorAuthentication

  before_action :require_admin_or_higher
  before_action :set_user, only: %i[ show toggle_ban ]

  def index
    @pagy, @users = pagy(User.where('role < ?', User.roles[current_user.role]), items: 10)
  end

  def show
  end

  def toggle_ban
    if @user == current_user || current_user.role_before_type_cast < @user.role_before_type_cast
      respond_to do |format|
        format.html { redirect_to moderator_user_path(@user), alert: 'You do not have permission to perform this action.' }
        format.turbo_stream { redirect_to moderator_user_path(@user), alert: 'You do not have permission to perform this action.' }
        format.json { render json: { error: 'You do not have permission to perform this action.' }, status: :forbidden }
      end
    else
      @user.update(banned: !@user.banned)
      respond_to do |format|
        format.html { redirect_to moderator_user_path(@user), notice: 'User ban status was successfully updated.' }
        format.turbo_stream { redirect_to moderator_user_path(@user), notice: 'User ban status was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users/developments_controller.rb
class Users::DevelopmentsController < ApplicationController
  before_action :set_development, only: %i[ show render_description ]

  # GET /developments or /developments.json
  def index
    items = 3

    lat = params[:latitude]
    lon = params[:longitude]
    distance = params[:distance] || 25  # Default to 50 miles if not provided
    if lat.present? && lon.present?
      @pagy, @developments = pagy(Development.within_distance_of(lat.to_f, lon.to_f, distance.to_i), items: items)
    else
      @pagy, @developments = pagy(Development.none, items: items)
    end
    @development_averages = @developments.map { |development| [development.id, development.review_average] }.to_h
  end

  # GET /developments/1 or /developments/1.json
  def show
    @image = @development.current_image
    @average = @development.review_average
  end


  def render_description
    render partial: "custom_description", locals: { development: @development }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_development
      @development = Development.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def development_params
      params.require(:development).permit(:name, :address, :acreage, :description, :website, :planned_start_date, :planned_end_date, :before_image, :after_image, :latitude, :longitude, :distance)
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!, except: %i[ show ]

  def new
    if current_user.profile
      redirect_to edit_profile_path(current_user.profile)
    else
      @profile = Profile.new
    end
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path(@profile), notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to profile_path(@profile), notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  private

  def profile_params
    params.require(:profile).permit(:username, :biography, :profile_picture)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |resource|
      if resource.save
        random_username = generate_random_username
        resource.create_profile!(username: random_username)
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    edit_profile_path(resource.profile)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def generate_random_username(length = 8)
    loop do
      username = Faker::Internet.username(specifier: length)
      break username unless Profile.exists?(username: username)
    end
  end
end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < ApplicationController
  # before_action :authenticate_user!, only: %i[ new edit update destroy create ]
  before_action :set_development
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /developments/:development_id/reviews
  def index
    # Pagination!!!
    @pagy, @reviews = pagy(@development.reviews, items: 5)
    @score_averages = @reviews.map { |review| [review.id, review.score_average] }.to_h
  end
  
  # GET /developments/:development_id/reviews/:id
  def show
    @score_average = @review.score_average
  end

  # GET /developments/:development_id/reviews/new
  def new
    @review = @development.reviews.build
    ScoreType.all.each do |score_type|
      @review.scores.build(score_type: score_type)
    end
  end

  # GET /developments/:development_id/reviews/:id/edit
  def edit
  end

  # POST /developments/:development_id/reviews
  def create
    @review = @development.reviews.build(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to development_review_url(@development, @review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: development_review_url(@development, @review) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developments/:development_id/reviews/:id
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to development_review_url(@development, @review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: development_review_url(@development, @review) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developments/:development_id/reviews/:id
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to development_reviews_url(@development), notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_development
    @development = Development.find(params[:development_id])
  end

  def set_review
    @review = @development.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :description, scores_attributes: [:id, :value, :score_type_id, :_destroy])
  end
end

app/controllers/users/scores_controller.rb
class Users::ScoresController < ApplicationController
  # before_action :authenticate_user!, only: %i[ edit update destroy new create ] 

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users/search_controller.rb
class Users::SearchController < ApplicationController
  def index
    @query = params[:query]
    @address = {
      street_address: params[:street_address],
      city: params[:city],
      state: params[:state],
      postal_code: params[:postal_code],
      country: params[:country]
    }

    if @query.present?
      # Combine address fields into a single address string
      @address_parts = [
        @address[:street_address],
        @address[:city],
        @address[:state],
        @address[:postal_code],
        @address[:country]
      ].compact.join(', ')

      # Search for Developments
      @pagy, @results = pagy(
        Development.where(
          "LOWER(name) LIKE ? OR LOWER(description) LIKE ?", "%#{@query.downcase}%", "%#{@query.downcase}%"
        ),
        items: 3
      )

      # If an address is provided, filter by proximity
      if address_parts.present?
        geocoded_address = Geocoder.search(address_parts).first
        if geocoded_address
          lat, lon = geocoded_address.latitude, geocoded_address.longitude
          distance = params[:radius] || 50
          @pagy, @results = pagy(
            Development.within_distance_of(lat, lon, distance.to_i),
            items: 3
          )
        end
      end

      if !@results.present?
        redirect_to search_index_path, notice: "The following search returned zero results."
      end
    end
  end
end

app/helpers/developments_helper.rb
module DevelopmentsHelper
end

app/helpers/moderator/developments_helper.rb
module Moderator::DevelopmentsHelper
end

app/helpers/moderator/users_helper.rb
module Moderator::UsersHelper
end

app/helpers/users/developments_helper.rb
module Users::DevelopmentsHelper
  def current_location
    {
      latitude: session[:latitude],
      longitude: session[:longitude]
    }
  end
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users/reviews_helper.rb
module Users::ReviewsHelper
end

app/helpers/users/scores_helper.rb
module Users::ScoresHelper
end

app/helpers/users/search_helper.rb
module Users::SearchHelper
end

app/views/users/developments/_custom_description.html.erb
<%= turbo_frame_tag "description" do %>
    <div class="flex flex-col gap-2 items-center justify-center w-full">
        <div class="p-4 w-full border border-gray-100 shadow-md">
            <div class="w-full">
                <h4 class="text-lg font-semibold">A <%= @development.acreage%> Acre Development</h4>
                <%= render "users/addresses/address", address: @development.address %>
            </div>
            <div class="mt-4 w-full" id="description">
                <h4 class="text-md pb-2 font-semibold">Description: </h4>
                <p class="text-md">
                <%= @development.description %>
                </p>
            </div>
        </div>
    </div>
<% end %>

app/views/users/developments/_development.html.erb
<div class="max-w-4xl w-full md:p-4 block">
    <div class="w-full border border-gray-100 shadow-md">
      <div class="p-0 md:p-4 w-full mb-4 md:mb-0">
        <%= image_tag @image, class: "h-72 w-full object-cover" %>
        <div class="w-full flex p-2 md:p-4 justify-between">
          <div class="flex flex-col">
            <h2 class="text-md md:text-xl font-semibold"><%= @development.name %>: </h2>
            <div class="flex self-center">
              <span class="text-md md:text-lg font-bold"><%= @average %></span>
              <svg aria-hidden="true" class="w-5 h-5 text-yellow-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="m12 2.694 2.119 6.857.109.352h7.294L15.898 14.2l-.277.212.103.333 2.135 6.909-5.556-4.244-.303-.232-.303.232-5.556 4.244 2.135-6.909.103-.333-.277-.212-5.624-4.296h7.295l.108-.352L12 2.694Z"></path>
              </svg>
            </div>
          </div>
          <% if user_signed_in? %>
            <%= link_to "Add a Review", new_development_review_path(@development), remote: true, data: { turbo_frame: "description" }, class: "flex justify-center items-center min-w-fit text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-xs md:text-sm md:px-5 md:py-2.5 md:me-2 md:mb-2 px-2 py-1 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
          <% else %>
            <%= link_to "Add a Review", new_user_session_path, class: "flex justify-center items-center min-w-fit text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-xs md:text-sm md:px-5 md:py-2.5 md:me-2 md:mb-2 px-2 py-1 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
          <% end %>
        </div>
        <ul data-controller="navigation" class="flex w-full gap-4 px-4">
          <li class="hover:underline text-black">
            <%= link_to "Description", render_description_path(@development), remote: true, class: "underline font-medium text-gray-600 hover:underline", data: { navigation_target: "link", turbo_frame: "description" } %>
          </li>
          <li class="hover:underline text-black">
            <%= link_to "Reviews", development_reviews_path(@development), class: "font-medium text-gray-600 hover:underline", data: { navigation_target: "link", turbo_frame: "description" } %>
          </li>
          <li class="hover:underline text-black">
            <button class="font-medium text-gray-600 hover:underline">Native Plants</button>
          </li>
        </ul>
      </div>
    </div>
    <div>
      <%= turbo_frame_tag "description" do %>
        <!-- Description -->
        <%= render "custom_description", development: @development %>
      <% end %>
  </div>
</div>
  

app/views/users/developments/_development_card.html.erb
<%= link_to development_path(development), class: "max-w-4xl mx-auto p-4 border border-gray-100 shadow-md block" do %>
  <div class="flex flex-wrap">
    <div class="w-full lg:w-2/3 flex items-center">
      <%= image_tag development.logo, alt: development.name, class: "mr-4 h-16 w-16 rounded-full" %>
      <div>
        <h2 class="text-xl font-bold"><%= development.name %></h2>
        <div class="flex items-center">
          <span class="pr-2 text-lg font-bold"><%= average %></span>
          <span class="text-yellow-400">
            <svg aria-hidden="true" class="w-5 h-5 text-yellow-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
              <path d="m12 2.694 2.119 6.857.109.352h7.294L15.898 14.2l-.277.212.103.333 2.135 6.909-5.556-4.244-.303-.232-.303.232-5.556 4.244 2.135-6.909.103-.333-.277-.212-5.624-4.296h7.295l.108-.352L12 2.694Z"></path>
            </svg>
          </span>
        </div>
      </div>
    </div>
    <div class="w-full lg:w-1/3 mt-4 lg:mt-0 flex justify-between">
      <div class="flex flex-col items-center hover:underline">
        <h3 class="text-lg font-bold"><%= development.reviews.count %></h3>
        <span class="text-gray-600">Reviews</span>
      </div>
      <div class="flex flex-col items-center">
        <h3 class="text-lg font-bold"><%= development.planned_start_date %></h3>
        <span class="text-gray-600">Start Date</span>
      </div>
    </div>
    <div class="w-full lg:w-1/3 mt-4">
      <span class="font-semibold">Location</span>
      <span class="block mt-1 text-gray-600">
        <%= render "users/addresses/address", address: development.address %>
      </span>
    </div>
    <div class="w-full lg:w-1/3 mt-4">
      <span class="font-semibold">Acreage Planned</span>
      <span class="block mt-1 text-gray-600"><%= development.acreage %></span>
    </div>
    <div class="w-full lg:w-1/3 mt-4">
      <span class="font-semibold">Native Ecosystem</span>
      <span class="block mt-1 text-gray-600"><%= development.ecosystem %></span>
    </div>
    <div class="w-full mt-4">
      <span class="font-semibold">Description</span>
      <p class="mt-2 text-gray-600">
        <%= development.description %>
      </p>
    </div>
  </div>
<% end %>

app/views/users/developments/_form.html.erb
<%= form_with(model: development, class: "contents") do |form| %>
  <% if development.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(development.errors.count, "error") %> prohibited this development from being saved:</h2>

      <ul>
        <% development.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :acreage %>
    <%= form.text_field :acreage, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :website %>
    <%= form.text_field :website, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :planned_start_date %>
    <%= form.date_field :planned_start_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :planned_end_date %>
    <%= form.date_field :planned_end_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :before_image %>
    <%= form.file_field :before_image %>
  </div>

  <div class="my-5">
    <%= form.label :after_image %>
    <%= form.file_field :after_image %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/developments/_paginator.html.erb
<nav aria-label="Page navigation example">
    <ul class="flex items-center -space-x-px text-sm">
    <% if params[:page].to_i > 1 %>
        <li>
        <%= link_to developments_path(page: params[:page].to_i - 1), class: "flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" do %>
            <span class="sr-only">Previous</span>
            <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
            </svg>
        <% end %>
        </li>
    <% end %>

    <% @page_numbers.each do |num| %>
        <li>
        <%= link_to developments_path(page: num ), class: "flex items-center justify-center px-3 h-8 leading-tight border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" + (num == params[:page].to_i ? " bg-blue-50 text-blue-600 border-blue-300" : " bg-white text-gray-500") do %>
            <%= num %>
        <% end %>
        </li>
    <% end %>

    <% if @developments.size == @per_page && params[:page].to_i < @page_numbers[-1] %>
        <li>
        <%= link_to developments_path(page: params[:page].to_i + 1), class: "flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" do %>
            <span class="sr-only">Next</span>
            <svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
        <% end %>
        </li>
    <% end %>
    </ul>
</nav>

app/views/users/developments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-center mb-4"> <!-- Centering container -->
    <%= render "paginator" %>
  </div> <!-- End of centering container -->

  <div class="flex justify-center mb-4">
    <%= render "users/search/form" %>
  </div>

  <div id="developments" class="min-w-full", data-controller="geolocation">
    <% @developments.each do |development| %>
      <%= render "development_card", development: development, average: @development_averages[development.id] %>
    <% end %>
  </div>
</div>

app/views/users/developments/show.html.erb
<div class="w-full flex justify-center items-center">
  <div class="flex items-center justify-center flex-col w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @development %>
  </div>
</div>