config/routes.rb
Rails.application.routes.draw do
  post 'set_location', to: 'locations#set'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Users Scopes
  scope module: "users" do 
    resources :profiles, only: %i[ show update edit ]

    resources :search, only: [ :index ]
    
    get '/developments/:id/render_description', to: 'developments#render_description', as: 'render_description'

    resources :developments, only: %i[ index show ] do
      resources :reviews do
        resources :scores
        resources :comments
      end
    end
  end
  
  # Moderation
  resources :moderator, only: %i[ index ]
  # Moderator Links
  namespace :moderator do
    resources :search, only: [ :index ]
    resources :developments do
      member do 
        patch :toggle_published
      end
      resources :reviews do
        resources :scores
        resources :comments
      end
    end
    # User management
    resources :users, only: %i[ index show ] do 
      member do
        patch :toggle_ban
      end
    end
  end


  # get 'admin', to: 'admin_panel#index'

  # Pages
  get "home", to: "pages#home"
  get "about_us", to: "pages#about"
  get "contact", to: "pages#contact"

  root 'pages#about'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
  
  after_create :build_default_profile

  has_many :reviews, dependent: :destroy

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

  enum :role, { user: 0, moderator: 1, admin: 2, owner: 3 }

  scope :banned, -> { where(banned: true) }

  # Override Devise's active_for_authentication? method
  def active_for_authentication?
    super && !banned?
  end

  # Provide a reason for the user being inactive
  def inactive_message
    !banned? ? super : :banned
  end


  private

  def build_default_profile
    create_profile # This will use factory defaults from Profile
  end
end
  

app/controllers/moderator/users_controller.rb
class Moderator::UsersController < ApplicationController
  include ModeratorAuthentication

  before_action :require_admin_or_higher
  before_action :set_user, only: %i[ show toggle_ban ]

  def index
    @pagy, @users = pagy(User.where('role < ?', User.roles[current_user.role]), items: 10)
  end

  def show
  end

  def toggle_ban
    if @user == current_user || current_user.role_before_type_cast < @user.role_before_type_cast
      respond_to do |format|
        format.html { redirect_to moderator_user_path(@user), alert: 'You do not have permission to perform this action.' }
        format.turbo_stream { redirect_to moderator_user_path(@user), alert: 'You do not have permission to perform this action.' }
        format.json { render json: { error: 'You do not have permission to perform this action.' }, status: :forbidden }
      end
    else
      @user.update(banned: !@user.banned)
      respond_to do |format|
        format.html { redirect_to moderator_user_path(@user), notice: 'User ban status was successfully updated.' }
        format.turbo_stream { redirect_to moderator_user_path(@user), notice: 'User ban status was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users/developments_controller.rb
class Users::DevelopmentsController < ApplicationController
  before_action :set_development, only: %i[ show render_description ]

  # GET /developments or /developments.json
  def index
    items = 3

    lat = params[:latitude]
    lon = params[:longitude]
    distance = params[:distance] || 25  # Default to 50 miles if not provided
    if lat.present? && lon.present?
      @pagy, @developments = pagy(Development.within_distance_of(lat.to_f, lon.to_f, distance.to_i), items: items)
    else
      @pagy, @developments = pagy(Development.none, items: items)
    end
    @development_averages = @developments.map { |development| [development.id, development.review_average] }.to_h
  end

  # GET /developments/1 or /developments/1.json
  def show
    @image = @development.current_image
    @average = @development.review_average
  end


  def render_description
    render partial: "custom_description", locals: { development: @development }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_development
      @development = Development.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def development_params
      params.require(:development).permit(:name, :address, :acreage, :description, :website, :planned_start_date, :planned_end_date, :before_image, :after_image, :latitude, :longitude, :distance)
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!, except: %i[ show ]

  def new
    if current_user.profile
      redirect_to edit_profile_path(current_user.profile)
    else
      @profile = Profile.new
    end
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path(@profile), notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to profile_path(@profile), notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  private

  def profile_params
    params.require(:profile).permit(:username, :biography, :profile_picture)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |resource|
      if resource.save
        random_username = generate_random_username
        resource.create_profile!(username: random_username)
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    edit_profile_path(resource.profile)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def generate_random_username(length = 8)
    loop do
      username = Faker::Internet.username(specifier: length)
      break username unless Profile.exists?(username: username)
    end
  end
end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < ApplicationController
  # before_action :authenticate_user!, only: %i[ new edit update destroy create ]
  before_action :set_development
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /developments/:development_id/reviews
  def index
    # Pagination!!!
    @pagy, @reviews = pagy(@development.reviews, items: 5)
    @score_averages = @reviews.map { |review| [review.id, review.score_average] }.to_h
  end
  
  # GET /developments/:development_id/reviews/:id
  def show
    @score_average = @review.score_average
  end

  # GET /developments/:development_id/reviews/new
  def new
    @review = @development.reviews.build
    ScoreType.all.each do |score_type|
      @review.scores.build(score_type: score_type)
    end
  end

  # GET /developments/:development_id/reviews/:id/edit
  def edit
  end

  # POST /developments/:development_id/reviews
  def create
    @review = @development.reviews.build(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to development_review_url(@development, @review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: development_review_url(@development, @review) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developments/:development_id/reviews/:id
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to development_review_url(@development, @review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: development_review_url(@development, @review) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developments/:development_id/reviews/:id
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to development_reviews_url(@development), notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_development
    @development = Development.find(params[:development_id])
  end

  def set_review
    @review = @development.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :description, scores_attributes: [:id, :value, :score_type_id, :_destroy])
  end
end

app/controllers/users/scores_controller.rb
class Users::ScoresController < ApplicationController
  # before_action :authenticate_user!, only: %i[ edit update destroy new create ] 

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users/search_controller.rb
class Users::SearchController < ApplicationController
  def index
    @query = params[:query]
    @address = {
      street_address: params[:street_address],
      city: params[:city],
      state: params[:state],
      postal_code: params[:postal_code],
      country: params[:country]
    }

    if @query.present?
      # Combine address fields into a single address string
      @address_parts = [
        @address[:street_address],
        @address[:city],
        @address[:state],
        @address[:postal_code],
        @address[:country]
      ].compact.join(', ')

      # Search for Developments
      @pagy, @results = pagy(
        Development.where(
          "LOWER(name) LIKE ? OR LOWER(description) LIKE ?", "%#{@query.downcase}%", "%#{@query.downcase}%"
        ),
        items: 3
      )

      # If an address is provided, filter by proximity
      if address_parts.present?
        geocoded_address = Geocoder.search(address_parts).first
        if geocoded_address
          lat, lon = geocoded_address.latitude, geocoded_address.longitude
          distance = params[:radius] || 50
          @pagy, @results = pagy(
            Development.within_distance_of(lat, lon, distance.to_i),
            items: 3
          )
        end
      end

      if !@results.present?
        redirect_to search_index_path, notice: "The following search returned zero results."
      end
    end
  end
end

app/helpers/moderator/users_helper.rb
module Moderator::UsersHelper
end

app/helpers/users/developments_helper.rb
module Users::DevelopmentsHelper
  def current_location
    {
      latitude: session[:latitude],
      longitude: session[:longitude]
    }
  end
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users/reviews_helper.rb
module Users::ReviewsHelper
end

app/helpers/users/scores_helper.rb
module Users::ScoresHelper
end

app/helpers/users/search_helper.rb
module Users::SearchHelper
end

app/views/users/shared/_footer.html.erb
<footer class="w-full p-4 bg-white border-t border-green-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-green-800 dark:border-green-600">
    <span class="text-sm text-green-700 sm:text-center dark:text-green-300">© 2024
        <%= link_to "ConeFlower", "#", class: "hover:underline" %>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-green-700 dark:text-green-300 sm:mt-0">
        <li>
            <a href="https://github.com/trustpizza/coneflower" class="hover:underline me-4 md:me-6">Open Source</a>
        </li>
        <li>
            <%= link_to "About", about_us_path, class: "hover:underline me-4 md:me-6" %>
        </li>
        <li>
            <a href="#" class="hidden hover:underline me-4 md:me-6">Licensing</a>
        </li>
        <li>
            <a href="#" class="hover:underline">Contact</a>
        </li>
    </ul>
</footer>

app/views/users/shared/_header.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between lg:grid lg:grid-cols-4 mx-auto p-4 px-8 gap-4">
    <!-- Root Url Section -->
    <%= link_to root_url, class: "flex items-center space-x-3 rtl:space-x-reverse" do %>
      <%= image_tag "favicon.png", class: "h-8", alt: "Coneflower Logo" %>
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-green-600 text-green-500 hover:underline">ConeFlower</span>
    <% end %>
    <!-- User nav section -->
    <div class="lg:justify-self-end flex items-center lg:order-2 space-x-3 lg:space-x-0 rtl:space-x-reverse">
      <% if user_signed_in? %>
        <button type="button" class="flex text-sm bg-gray-800 rounded-full lg:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
          <span class="sr-only">Open user menu</span>
          <% if current_user.profile.profile_picture.attached? %>
            <%= image_tag current_user.profile.profile_picture, class: "w-8 h-8 rounded-full", alt: "User Photo" %>
          <% else %>
            <%= image_tag "default-user", class: "w-8 h-8 rounded-full bg-white border", alt: "User Photo" %>
          <% end %>
        </button>

        <!-- Dropdown menu -->
          <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
            <div class="px-4 py-3">
              <span class="block text-sm text-gray-900 dark:text-white">
                <%= current_user.profile.username %>
              </span>
              <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">
                <%= current_user.email %>
              </span>
            </div>
            <ul class="py-2" aria-labelledby="user-menu-button">
              <li>
                <%= link_to "Settings", edit_profile_path(current_user.profile), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
              </li>
              <li>
                <%= link_to "Sign Out", destroy_user_session_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
              </li>
            </ul>
          </div>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "block py-2 px-3 text-green-600 rounded hover:bg-green-100 lg:hover:underline lg:hover:bg-transparent lg:hover:text-green-700 lg:p-0 lg:dark:hover:text-green-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700" %>
      <% end %>

      <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
      </button>
    </div>
    <!-- Nav Links -->
    <div class="lg:col-span-2 items-center justify-between hidden w-full lg:flex lg:w-auto lg:order-1" id="navbar-user">
      <ul class="lg:w-full lg:justify-around flex flex-col font-medium p-4 lg:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 lg:space-x-8 rtl:space-x-reverse lg:flex-row lg:mt-0 lg:border-0 lg:bg-white dark:bg-gray-800 lg:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <%= link_to "Home", root_url, class: "block py-2 px-3 text-green-600 rounded hover:bg-green-100 lg:hover:underline lg:hover:bg-transparent lg:hover:text-green-700 lg:p-0 lg:dark:hover:text-green-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700" %>
        </li>
        <li>
          <%= link_to "About", about_us_url, class: "block py-2 px-3 text-green-600 rounded hover:bg-green-100 lg:hover:underline lg:hover:bg-transparent lg:hover:text-green-700 lg:p-0 lg:dark:hover:text-green-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700" %>
        </li>
        <li>
          <%= link_to "Developments", developments_url, class: "block py-2 px-3 text-green-600 rounded hover:bg-green-100 lg:hover:underline lg:hover:bg-transparent lg:hover:text-green-700 lg:p-0 lg:dark:hover:text-green-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700" %>
        </li>
        <% if user_signed_in? %>
          <li>
              <% if current_user.moderator? || current_user.admin? || current_user.owner? %>
                <%= link_to 'Moderation', moderator_index_path, class: 'block py-2 px-3 text-green-600 rounded hover:bg-green-100 lg:hover:underline lg:hover:bg-transparent lg:hover:text-green-700 lg:p-0 lg:dark:hover:text-green-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700' %>
              <% end %>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>