config/routes.rb
Rails.application.routes.draw do
  post 'set_location', to: 'locations#set'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Users Scopes
  scope module: "users" do 
    resources :profiles, only: %i[ show update edit ]

    resources :search, only: [ :index ]
    
    get '/developments/:id/render_description', to: 'developments#render_description', as: 'render_description'

    resources :developments, only: %i[ index show ] do
      resources :reviews do
        resources :scores
        resources :comments
      end
    end
  end
  
  # Moderation
  resources :moderator, only: %i[ index ]
  # Moderator Links
  namespace :moderator do
    resources :search, only: [ :index ]
    resources :developments do
      member do 
        patch :toggle_published
      end
      resources :reviews do
        resources :scores
        resources :comments
      end
    end
    # User management
    resources :users, only: %i[ index show ] do 
      member do
        patch :toggle_ban
      end
    end
  end


  # get 'admin', to: 'admin_panel#index'

  # Pages
  get "home", to: "pages#home"
  get "about_us", to: "pages#about"
  get "contact", to: "pages#contact"

  root 'pages#about'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
  
  after_create :build_default_profile

  has_many :reviews, dependent: :destroy

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

  enum :role, { user: 0, moderator: 1, admin: 2, owner: 3 }

  scope :banned, -> { where(banned: true) }

  # Override Devise's active_for_authentication? method
  def active_for_authentication?
    super && !banned?
  end

  # Provide a reason for the user being inactive
  def inactive_message
    !banned? ? super : :banned
  end


  private

  def build_default_profile
    create_profile # This will use factory defaults from Profile
  end
end
  

app/controllers/moderator/reviews_controller.rb
class Moderator::ReviewsController < ModeratorController
  before_action :set_development
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /developments/:development_id/reviews
  def index
    # Pagination!!!
    @pagy, @reviews = pagy(@development.reviews, items: 5)
    @score_averages = @reviews.map { |review| [review.id, review.score_average] }.to_h
  end
  
  # GET /developments/:development_id/reviews/:id
  def show
    @score_average = @review.score_average
  end

  # GET /developments/:development_id/reviews/new
  def new
    @review = @development.reviews.build
    ScoreType.all.each do |score_type|
      @review.scores.build(score_type: score_type)
    end
  end

  # GET /developments/:development_id/reviews/:id/edit
  def edit
  end

  # PATCH/PUT /developments/:development_id/reviews/:id
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to development_review_url(@development, @review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: development_review_url(@development, @review) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developments/:development_id/reviews/:id
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to development_reviews_url(@development), notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_development
    @development = Development.find(params[:development_id])
  end

  def set_review
    @review = @development.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :description, scores_attributes: [:id, :value, :score_type_id, :_destroy])
  end
end

app/controllers/moderator/users_controller.rb
class Moderator::UsersController < ApplicationController
  include ModeratorAuthentication

  before_action :require_admin_or_higher
  before_action :set_user, only: %i[ show toggle_ban ]

  def index
    @pagy, @users = pagy(User.where('role < ?', User.roles[current_user.role]), items: 10)
  end

  def show
  end

  def toggle_ban
    if @user == current_user || current_user.role_before_type_cast < @user.role_before_type_cast
      respond_to do |format|
        format.html { redirect_to moderator_user_path(@user), alert: 'You do not have permission to perform this action.' }
        format.turbo_stream { redirect_to moderator_user_path(@user), alert: 'You do not have permission to perform this action.' }
        format.json { render json: { error: 'You do not have permission to perform this action.' }, status: :forbidden }
      end
    else
      @user.update(banned: !@user.banned)
      respond_to do |format|
        format.html { redirect_to moderator_user_path(@user), notice: 'User ban status was successfully updated.' }
        format.turbo_stream { redirect_to moderator_user_path(@user), notice: 'User ban status was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users/developments_controller.rb
class Users::DevelopmentsController < ApplicationController
  before_action :set_development, only: %i[ show render_description ]

  # GET /developments or /developments.json
  def index
    items = 3

    lat = params[:latitude]
    lon = params[:longitude]
    distance = params[:distance] || 25  # Default to 50 miles if not provided
    if lat.present? && lon.present?
      @pagy, @developments = pagy(Development.within_distance_of(lat.to_f, lon.to_f, distance.to_i), items: items)
    else
      @pagy, @developments = pagy(Development.none, items: items)
    end
    @development_averages = @developments.map { |development| [development.id, development.review_average] }.to_h
  end

  # GET /developments/1 or /developments/1.json
  def show
    @image = @development.current_image
    @average = @development.review_average
  end


  def render_description
    render partial: "custom_description", locals: { development: @development }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_development
      @development = Development.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def development_params
      params.require(:development).permit(:name, :address, :acreage, :description, :website, :planned_start_date, :planned_end_date, :before_image, :after_image, :latitude, :longitude, :distance)
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!, except: %i[ show ]

  def new
    if current_user.profile
      redirect_to edit_profile_path(current_user.profile)
    else
      @profile = Profile.new
    end
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path(@profile), notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to profile_path(@profile), notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  private

  def profile_params
    params.require(:profile).permit(:username, :biography, :profile_picture)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |resource|
      if resource.save
        random_username = generate_random_username
        resource.create_profile!(username: random_username)
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    edit_profile_path(resource.profile)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def generate_random_username(length = 8)
    loop do
      username = Faker::Internet.username(specifier: length)
      break username unless Profile.exists?(username: username)
    end
  end
end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < ApplicationController
  # before_action :authenticate_user!, only: %i[ new edit update destroy create ]
  before_action :set_development
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /developments/:development_id/reviews
  def index
    # Pagination!!!
    @pagy, @reviews = pagy(@development.reviews, items: 5)
    @score_averages = @reviews.map { |review| [review.id, review.score_average] }.to_h
  end
  
  # GET /developments/:development_id/reviews/:id
  def show
    @score_average = @review.score_average
  end

  # GET /developments/:development_id/reviews/new
  def new
    @review = @development.reviews.build
    ScoreType.all.each do |score_type|
      @review.scores.build(score_type: score_type)
    end
  end

  # GET /developments/:development_id/reviews/:id/edit
  def edit
  end

  # POST /developments/:development_id/reviews
  def create
    @review = @development.reviews.build(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to development_review_url(@development, @review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: development_review_url(@development, @review) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developments/:development_id/reviews/:id
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to development_review_url(@development, @review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: development_review_url(@development, @review) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developments/:development_id/reviews/:id
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to development_reviews_url(@development), notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_development
    @development = Development.find(params[:development_id])
  end

  def set_review
    @review = @development.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :description, scores_attributes: [:id, :value, :score_type_id, :_destroy])
  end
end

app/controllers/users/scores_controller.rb
class Users::ScoresController < ApplicationController
  # before_action :authenticate_user!, only: %i[ edit update destroy new create ] 

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users/search_controller.rb
class Users::SearchController < ApplicationController
  def index
    @query = params[:query]
    @address = {
      street_address: params[:street_address],
      city: params[:city],
      state: params[:state],
      postal_code: params[:postal_code],
      country: params[:country]
    }

    if @query.present?
      # Combine address fields into a single address string
      @address_parts = [
        @address[:street_address],
        @address[:city],
        @address[:state],
        @address[:postal_code],
        @address[:country]
      ].compact.join(', ')

      # Search for Developments
      @pagy, @results = pagy(
        Development.where(
          "LOWER(name) LIKE ? OR LOWER(description) LIKE ?", "%#{@query.downcase}%", "%#{@query.downcase}%"
        ),
        items: 3
      )

      # If an address is provided, filter by proximity
      if address_parts.present?
        geocoded_address = Geocoder.search(address_parts).first
        if geocoded_address
          lat, lon = geocoded_address.latitude, geocoded_address.longitude
          distance = params[:radius] || 50
          @pagy, @results = pagy(
            Development.within_distance_of(lat, lon, distance.to_i),
            items: 3
          )
        end
      end

      if !@results.present?
        redirect_to search_index_path, notice: "The following search returned zero results."
      end
    end
  end
end

app/helpers/moderator/reviews_helper.rb
module Moderator::ReviewsHelper
end

app/helpers/moderator/users_helper.rb
module Moderator::UsersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users/developments_helper.rb
module Users::DevelopmentsHelper
  def current_location
    {
      latitude: session[:latitude],
      longitude: session[:longitude]
    }
  end
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users/reviews_helper.rb
module Users::ReviewsHelper
end

app/helpers/users/scores_helper.rb
module Users::ScoresHelper
end

app/helpers/users/search_helper.rb
module Users::SearchHelper
end

app/views/users/reviews/_form.html.erb
<%= form_with(model: [@development, @review], local: true, class: "space-y-8") do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="bg-red-50 border border-red-400 text-red-700 px-4 py-3 rounded-lg mt-3">
      <h2 class="font-bold mb-2"><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul class="list-disc list-inside">
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="bg-white p-6 rounded-lg shadow-md space-y-4">
    <div class="space-y-2">
      <%= form.label :title, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :title, class: "mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>

    <div class="space-y-2">
      <%= form.label :description, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_area :description, class: "mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>

    <h3 class="text-lg font-medium text-gray-900">Scores</h3>
    <div class="space-y-4">
      <%= form.fields_for :scores do |score_fields| %>
        <div class="my-5">
          <%= score_fields.label :value, score_fields.object.score_type.name %>
          <%= score_fields.select :value, options_for_select(1..5), {}, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2" %>
          <%= score_fields.hidden_field :score_type_id %>
        </div>
      <% end %>
    </div>

    <div class="flex justify-end">
      <%= form.submit "Submit", class: "rounded-lg py-2 px-4 bg-blue-600 text-white font-medium hover:bg-blue-700 focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
    </div>
  </div>
<% end %>

app/views/users/reviews/_review.html.erb
<div class="w-full flex flex-col bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-7000 dark:bg-gray-800 dark:hover:bg-gray-700">
    <%= link_to development_review_path(@development, review), data: {turbo: false} do %>
    
      <!-- If there's an image, it should display properly -->
      <%# if review.image.present? %>
        <%#= image_tag review.image, class: "object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" %>
      <%# end %>
    
      <div class="flex-grow flex flex-col justify-between p-4 leading-normal">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          <%= review.title %>
        </h5>
    
        <!-- Reviewer Block -->
        <%= link_to profile_path(review.user.profile), class: "text-blue-400 dark:text-white hover:underline", data: { turbo: false } do %>
          <%= review.user.profile.username %>
        <% end %>
    
        <div class="flex items-center mt-2.5 mb-5">
          <div class="flex items-center space-x-1 rtl:space-x-reverse">
            <% review_average.to_i.times do %>
              <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
              </svg>
            <% end %>
            <% (5 - review_average.to_i).times do %>
              <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"></path>
              </svg>
            <% end %>
          </div>
          <span class="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ms-3">
            <%= review_average %>
          </span>
        </div>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
          <%= review.description %>
        </p>
      </div>
    
    <% end %>
</div>

app/views/users/reviews/index.html.erb
<%= turbo_frame_tag "description" do %>
  <div class="mt-2 flex flex-col gap-2 items-center justify-center w-full">
    <%= render "paginator" %>
    <% @reviews.each do |review| %>
      <%= render "review", review: review, review_average: @score_averages[review.id] %>
    <% end %>
  </div>
<% end %>

app/views/users/reviews/new.html.erb
<%= turbo_frame_tag "description" do %>
    <%= render "form", review: @review %>
<% end %>

app/views/users/reviews/show.html.erb
<div class="max-w-3xl mx-auto bg-white p-6 rounded-lg shadow-lg">
    <!-- Review Section -->
    <div class="mb-6">
        <h2 class="text-2xl font-bold mb-2"><%= @review.title %></h2>
        <p class="text-gray-700 mb-4"><%= @review.description %></p>
        <div class="flex items-center">
            <span class="text-yellow-400 flex">
                <% @score_average.to_i.times do %>
                    <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                        <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                    </svg>
                <% end %>
                <% (5 - @score_average.to_i).times do %>
                    <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                        <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"></path>
                    </svg>
                <% end %>
            </span>
            <span class="ml-2 text-gray-600"><%= @score_average %></span>
        </div>
    </div>

    <!-- Scores Section -->
    <div>
        <% @review.scores.each do |score| %>
            <%= render "users/scores/score", score: score %>
        <% end %>
    </div>
</div>