config/routes.rb
Rails.application.routes.draw do
  post 'set_location', to: 'locations#set'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Users Scopes
  scope module: "users" do 
    resources :profiles, only: %i[ show update edit ]

    resources :search, only: [ :index ]
    
    get '/developments/:id/render_description', to: 'developments#render_description', as: 'render_description'

    resources :developments, only: %i[ index show ] do
      resources :reviews do
        resources :scores
        resources :comments
      end
    end
  end
  
  # Moderation
  resources :moderator, only: %i[ index ]
  # Moderator Links
  namespace :moderator do
    resources :search, only: [ :index ]
    resources :developments do
      member do 
        patch :toggle_published
      end
      resources :reviews do
        resources :scores
        resources :comments
      end
    end
    # User management
    resources :users, only: %i[ index show ] do 
      member do
        patch :toggle_ban
      end
    end
  end


  # get 'admin', to: 'admin_panel#index'

  # Pages
  get "home", to: "pages#home"
  get "about_us", to: "pages#about"
  get "contact", to: "pages#contact"

  root 'pages#about'
end

app/controllers/moderator/comments_controller.rb
class Moderator::CommentsController < ModeratorController
  
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/moderator/developments_controller.rb
class Moderator::DevelopmentsController < ModeratorController
  before_action :set_development, only: %i[ edit update show destroy toggle_published ]
  before_action :require_admin_or_higher, only: %i[ destroy ]

  def index
    @pagy, @developments = pagy(Development.all, items: 3)
    @development_averages = @developments.map { |development| [development.id, development.review_average] }.to_h
  end

  def show
    @image = @development.current_image
    @average = @development.review_average
  end

  def edit
  end 

  def update
    if @development.update(development_params)
      redirect_to moderator_development_path(@development), notice: 'Development was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @development.destroy
    respond_to do |format|
      format.html
      format.turbo_stream
    end
    redirect_to moderator_developments_path
  end

  def toggle_published
    @development.update(published: !@development.published)
    respond_to do |format|
      format.html { redirect_to moderator_development_url(@development), notice: 'Development status was successfully updated.' }
      format.turbo_stream { redirect_to moderator_development_url(@development), notice: "Development status successfully updated." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_development
    @development = Development.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def development_params
    params.require(:development).permit(:name, :address, :acreage, :description, :website, :planned_start_date, :planned_end_date, :before_image, :after_image, :latitude, :longitude, address_attributes: [:id, :street_address, :city, :state, :postal_code, :country])
  end
end

app/controllers/moderator/reviews_controller.rb
class Moderator::ReviewsController < ModeratorController
  before_action :set_development
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /developments/:development_id/reviews
  def index
    # Pagination!!!
    @pagy, @reviews = pagy(@development.reviews, items: 5)
    @score_averages = @reviews.map { |review| [review.id, review.score_average] }.to_h
  end
  
  # GET /developments/:development_id/reviews/:id
  def show
    @score_average = @review.score_average
  end

  # GET /developments/:development_id/reviews/new
  def new
    @review = @development.reviews.build
    ScoreType.all.each do |score_type|
      @review.scores.build(score_type: score_type)
    end
  end

  # GET /developments/:development_id/reviews/:id/edit
  def edit
  end

  # PATCH/PUT /developments/:development_id/reviews/:id
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to development_review_url(@development, @review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: development_review_url(@development, @review) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developments/:development_id/reviews/:id
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to development_reviews_url(@development), notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_development
    @development = Development.find(params[:development_id])
  end

  def set_review
    @review = @development.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :description, scores_attributes: [:id, :value, :score_type_id, :_destroy])
  end
end

app/controllers/moderator/scores_controller.rb
class Moderator::ScoresController < ModeratorController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/moderator/search_controller.rb
class Moderator::SearchController < ApplicationController
  def index
    @query = params[:query]
    


    @search_type = params[:search_type]
    @results = []

    if @query.present? && @search_type.present?
      # if @query.length < 3
      if false # not currently working
        flash.now[:notice] = "NO!"
        redirect_back(fallback_location: moderator_index_path, alert: "No")
      else
        case @search_type
        when "users"
          @pagy, @results = pagy(
            User.where("LOWER(email) LIKE ?", "%#{@query.downcase}%"),
            items: 3
          )
        else
          @pagy, @results = pagy(
            Development.where(
              "LOWER(name) LIKE ? OR LOWER(description) LIKE ?", "%#{@query.downcase}%", "%#{@query.downcase}%"
            ),
            items: 3
          )
        end
      end
    end
  end

  private

  def search_params
    params.require(:search).permit(:query, :search_type)
  end

end

app/controllers/moderator/users_controller.rb
class Moderator::UsersController < ApplicationController
  include ModeratorAuthentication

  before_action :require_admin_or_higher
  before_action :set_user, only: %i[ show toggle_ban ]

  def index
    @pagy, @users = pagy(User.where('role < ?', User.roles[current_user.role]), items: 10)
  end

  def show
  end

  def toggle_ban
    if @user == current_user || current_user.role_before_type_cast < @user.role_before_type_cast
      respond_to do |format|
        format.html { redirect_to moderator_user_path(@user), alert: 'You do not have permission to perform this action.' }
        format.turbo_stream { redirect_to moderator_user_path(@user), alert: 'You do not have permission to perform this action.' }
        format.json { render json: { error: 'You do not have permission to perform this action.' }, status: :forbidden }
      end
    else
      @user.update(banned: !@user.banned)
      respond_to do |format|
        format.html { redirect_to moderator_user_path(@user), notice: 'User ban status was successfully updated.' }
        format.turbo_stream { redirect_to moderator_user_path(@user), notice: 'User ban status was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/moderator_controller.rb
class ModeratorController < ApplicationController
  include ModeratorAuthentication
  layout "moderator"

  def index
    redirect_to moderator_developments_path
  end
  
end

app/helpers/moderator/comments_helper.rb
module Moderator::CommentsHelper
end

app/helpers/moderator/developments_helper.rb
module Moderator::DevelopmentsHelper
end

app/helpers/moderator/reviews_helper.rb
module Moderator::ReviewsHelper
end

app/helpers/moderator/scores_helper.rb
module Moderator::ScoresHelper
end

app/helpers/moderator/search_helper.rb
module Moderator::SearchHelper
end

app/helpers/moderator/users_helper.rb
module Moderator::UsersHelper
end

app/helpers/moderator_helper.rb
module ModeratorHelper
end

app/views/moderator/shared/_sidebar.html.erb
<nav class="fixed top-0 z-50 w-full bg-white border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700">
  <div class="px-3 py-3 lg:px-5 lg:pl-3">
    <div class="flex items-center justify-between">
      <div class="flex items-center justify-start rtl:justify-end">
        <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
            <span class="sr-only">Open sidebar</span>
            <%= image_tag "icons/hamburger-menu-icon.svg", class: "h-6 w-6" %>
         </button>
         <%= link_to root_url, class: "flex ms-2 md:me-24" do %>
            <%= image_tag "favicon.png", class: "h-8 me-3" %>
            <span class="self-center text-xl font-semibold sm:text-2xl whitespace-nowrap dark:text-white">ConeFlower</span>
         <% end %>
      </div>
      <div class="flex items-center">
          <div class="flex items-center ms-3">
            <div>
              <button type="button" class="flex text-sm bg-gray-800 rounded-full focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" aria-expanded="false" data-dropdown-toggle="dropdown-user">
                <span class="sr-only">Open user menu</span>
                <img class="w-8 h-8 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-5.jpg" alt="user photo">
              </button>
            </div>
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600" id="dropdown-user">
              <div class="px-4 py-3" role="none">
                <p class="text-sm text-gray-900 dark:text-white" role="none">
                  Username
                </p>
                <p class="text-sm font-medium text-gray-900 truncate dark:text-gray-300" role="none">
                  <%= current_user.email %>
                </p>
              </div>
              <ul class="py-1" role="none">
                <li>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Settings</a>
                </li>
                <li>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Earnings</a>
                </li>
                <li>
                  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "w-full text-left  block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white", data: { turbo: false } %>
                </li>
              </ul>
            </div>
          </div>
        </div>
    </div>
  </div>
</nav>

<!--
 * Necessary Features:
    * Users
    * Developments
    * 
-->

<aside id="logo-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-gray-200 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700" aria-label="Sidebar">
   <div class="h-full px-3 pb-4 overflow-y-auto bg-white dark:bg-gray-800">
      <ul class="space-y-2 font-medium">
         <li>
            <%= link_to moderator_index_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do %>
               <%= image_tag "icons/dashboard.svg", class: "w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" %>
               <span class="ms-3">Dashboard</span>
            <% end %>
         </li>
         <li>
            <%= link_to moderator_developments_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do %>
               <%= image_tag "icons/home.svg", class: "w-5 h-5" %>
               <span class="ms-3">Developments</span>
            <% end %>
         </li>
         <% if current_user.admin? || current_user.owner? %>
         <li>
            <%= link_to moderator_users_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do  %>
              <%= image_tag "icons/person.svg", class: "flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" %>
              <span class="ms-3">Users</span>
            <% end %>
         </li>
         <% end %>
      </ul>
   </div>
</aside>